name: MyFirstWorkflow

on: workflow_dispatch

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello"
      - name: Calculate
        run: expr 90 + 90
      - name: check OS info of runner
        run: cat /etc/os-release