name: MyFirstWorkflow

on: push

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Pushing code to Repo
        run: git clone https://github.com/Kajal-Makhija/GitHub-Actions.git

      - name: Validating the code
        run: |
          cd GitHub-Actions
          chmod +x new.sh
          ./new.sh  

# hjsdjhsdjhd
